{{- if .Values.serviceAccount.create }}
{{- range $component := list "core" "ingestion" "worker" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vaurd-agent.fullname" $ }}-{{ $component }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vaurd-agent.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
